from typing import Literal

from oneepis_api.core.patient_scoped_route_inventory_types import PatientScopedRoute


def _write(
    method: Literal["POST", "PATCH", "DELETE"],
    path_template: str,
    surface: str,
    write_abac_dev_only: bool = False,
) -> PatientScopedRoute:
    return PatientScopedRoute(
        method,
        path_template,
        surface,
        True,
        False,
        False,
        True,
        write_abac_dev_only,
        False,
    )


PATIENT_SCOPED_WRITE_ROUTES: tuple[PatientScopedRoute, ...] = (
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/clinical-entries",
        "clinical_entries",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/clinical-entries/{entry_id}",
        "clinical_entries",
        write_abac_dev_only=True,
    ),
    _write(
        "DELETE",
        "/api/v1/patients/{patient_id}/clinical-entries/{entry_id}",
        "clinical_entries",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/clinical-events",
        "clinical_events",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/clinical-events/{event_id}",
        "clinical_events",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/clinical-orders",
        "clinical_orders",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/clinical-orders/{order_id}",
        "clinical_orders",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/vital-signs",
        "vital_signs",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/vital-signs/{vital_sign_id}",
        "vital_signs",
        write_abac_dev_only=True,
    ),
    _write(
        "DELETE",
        "/api/v1/patients/{patient_id}/vital-signs/{vital_sign_id}",
        "vital_signs",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/clinical-risks",
        "clinical_risks",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/clinical-risks/{risk_id}",
        "clinical_risks",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/medications",
        "medications",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/medications/{medication_id}",
        "medications",
        write_abac_dev_only=True,
    ),
    _write(
        "DELETE",
        "/api/v1/patients/{patient_id}/medications/{medication_id}",
        "medications",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/allergies",
        "allergies",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/allergies/{allergy_id}",
        "allergies",
        write_abac_dev_only=True,
    ),
    _write(
        "DELETE",
        "/api/v1/patients/{patient_id}/allergies/{allergy_id}",
        "allergies",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/problems",
        "active_problems",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/problems/{problem_id}",
        "active_problems",
        write_abac_dev_only=True,
    ),
    _write(
        "DELETE",
        "/api/v1/patients/{patient_id}/problems/{problem_id}",
        "active_problems",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/encounters",
        "encounters",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/encounters/{encounter_id}",
        "encounters",
        write_abac_dev_only=True,
    ),
    _write(
        "DELETE",
        "/api/v1/patients/{patient_id}/encounters/{encounter_id}",
        "encounters",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/appointments",
        "appointments",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/appointments/{appointment_id}",
        "appointments",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/patients/{patient_id}/lab-panels",
        "lab_panels_results",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/lab-panels/{panel_id}",
        "lab_panels_results",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/patients/{patient_id}/lab-panels/{panel_id}/results/{result_id}",
        "lab_panels_results",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/hospitalization/patients/{patient_id}/daily-sheets",
        "hospital_daily_sheets",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/hospitalization/patients/{patient_id}/daily-sheets/{sheet_id}",
        "hospital_daily_sheets",
        write_abac_dev_only=True,
    ),
    _write(
        "POST",
        "/api/v1/hospitalization/patients/{patient_id}/indications",
        "hospital_indications",
        write_abac_dev_only=True,
    ),
    _write(
        "PATCH",
        "/api/v1/hospitalization/patients/{patient_id}/indications/{indication_id}",
        "hospital_indications",
        write_abac_dev_only=True,
    ),
)
