export type ScreenDomain = "auth" | "configuracion" | "consulta" | "hospitalizacion" | "pacientes" | "print";
export type ScreenLifecycle = "complete" | "prepared" | "blocked";
export type ScreenKind = "app" | "print";
export type ScreenWritePolicy = "none" | "existing-api" | "blocked";
export type ScreenPaperPolicy = "none" | "carta";
export type ScreenPrintClinicalUse = "development-only" | "blocked";

export type ScreenCapability = {
  route: string;
  domain: ScreenDomain;
  lifecycle: ScreenLifecycle;
  screenKind: ScreenKind;
  writePolicy: ScreenWritePolicy;
  paperPolicy: ScreenPaperPolicy;
  printRoute?: string;
  printOwnerEntity?: string;
  printReadModel?: string;
  printApiClient?: string;
  printDocumentState?: string;
  printClinicalUse?: ScreenPrintClinicalUse;
  apiTestEvidence?: string[];
  blockExpectation?: string[];
};

export const screenCapabilities: ScreenCapability[] = [
  {
    route: "/",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/login",
    domain: "auth",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/nuevo",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/estado",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]/ficha",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "carta",
    printRoute: "/print/pacientes/[patientId]/ficha",
  },
  {
    route: "/pacientes/[patientId]/eventos",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_events.py"],
  },
  {
    route: "/pacientes/[patientId]/ai-chart",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: [
      "apps/api/tests/test_patient_ai_patch.py",
      "apps/api/tests/test_patient_ai_event_proposals.py",
    ],
  },
  {
    route: "/pacientes/[patientId]/encuentros",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/encuentros/nuevo",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_encounters.py"],
  },
  {
    route: "/pacientes/[patientId]/evoluciones",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/evoluciones/nueva",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "carta",
    printRoute: "/print/pacientes/[patientId]/evolucion/[entryId]",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]/evoluciones/desde-eventos",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "carta",
    printRoute: "/print/pacientes/[patientId]/evolucion/[entryId]",
    apiTestEvidence: ["apps/api/tests/test_patient_ai_patch.py"],
  },
  {
    route: "/pacientes/[patientId]/problemas",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/problemas/nuevo",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]/alergias",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/alergias/nueva",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]/medicacion",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/medicacion/nueva",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]/signos-vitales",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/signos-vitales/nuevo",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/pacientes/[patientId]/documentos",
    domain: "pacientes",
    lifecycle: "prepared",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/ia",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/pacientes/[patientId]/auditoria",
    domain: "pacientes",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/hospitalizacion",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/hospitalizacion/camas",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_hospital_beds.py"],
  },
  {
    route: "/hospitalizacion/camas/nueva",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "none",
    apiTestEvidence: ["apps/api/tests/test_hospital_beds.py"],
  },
  {
    route: "/hospitalizacion/rondas",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "carta",
    printRoute: "/print/hospitalizacion/rondas",
  },
  {
    route: "/hospitalizacion/pacientes/[patientId]/hoja-diaria",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "carta",
    printRoute: "/print/hospitalizacion/pacientes/[patientId]/hoja-diaria/[sheetId]",
    apiTestEvidence: ["apps/api/tests/test_hospital_daily_sheets.py"],
  },
  {
    route: "/hospitalizacion/pacientes/[patientId]/hoja-diaria/[sheetId]/editar",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "carta",
    printRoute: "/print/hospitalizacion/pacientes/[patientId]/hoja-diaria/[sheetId]",
    apiTestEvidence: ["apps/api/tests/test_hospital_daily_sheets.py"],
  },
  {
    route: "/hospitalizacion/pacientes/[patientId]/indicaciones",
    domain: "hospitalizacion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "carta",
    printRoute: "/print/hospitalizacion/pacientes/[patientId]/indicacion/[indicationId]",
    apiTestEvidence: ["apps/api/tests/test_hospital_indications.py"],
  },
  {
    route: "/consulta",
    domain: "consulta",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/consulta/agenda",
    domain: "consulta",
    lifecycle: "prepared",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/consulta/pacientes/[patientId]/atencion",
    domain: "consulta",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "existing-api",
    paperPolicy: "carta",
    printRoute: "/print/pacientes/[patientId]/evolucion/[entryId]",
    apiTestEvidence: ["apps/api/tests/test_encounters.py", "apps/api/tests/test_patient_record.py"],
  },
  {
    route: "/consulta/pacientes/[patientId]/resumen",
    domain: "consulta",
    lifecycle: "prepared",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "carta",
    printRoute: "/print/pacientes/[patientId]/resumen",
  },
  {
    route: "/configuracion",
    domain: "configuracion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/configuracion/apariencia",
    domain: "configuracion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/configuracion/ia",
    domain: "configuracion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/configuracion/api",
    domain: "configuracion",
    lifecycle: "complete",
    screenKind: "app",
    writePolicy: "none",
    paperPolicy: "none",
  },
  {
    route: "/print/pacientes/[patientId]/ficha",
    domain: "print",
    lifecycle: "complete",
    screenKind: "print",
    writePolicy: "none",
    paperPolicy: "carta",
    printOwnerEntity: "PatientRecordSnapshot",
    printReadModel: "GET /api/v1/patients/{patient_id}/record",
    printApiClient: "apps/web/src/lib/api/patients.ts:getPatientRecord",
    printDocumentState: "Documento de desarrollo / no uso clinico real",
    printClinicalUse: "development-only",
  },
  {
    route: "/print/pacientes/[patientId]/evolucion/[entryId]",
    domain: "print",
    lifecycle: "complete",
    screenKind: "print",
    writePolicy: "none",
    paperPolicy: "carta",
    printOwnerEntity: "ClinicalEntry via PatientRecordSnapshot.recent_entries",
    printReadModel: "GET /api/v1/patients/{patient_id}/record",
    printApiClient: "apps/web/src/lib/api/patients.ts:getPatientRecord",
    printDocumentState: "Borrador/firmada/enmendada visible; sin firma legal digital",
    printClinicalUse: "development-only",
  },
  {
    route: "/print/pacientes/[patientId]/resumen",
    domain: "print",
    lifecycle: "complete",
    screenKind: "print",
    writePolicy: "none",
    paperPolicy: "carta",
    printOwnerEntity: "PatientRecordSnapshot",
    printReadModel: "GET /api/v1/patients/{patient_id}/record",
    printApiClient: "apps/web/src/lib/api/patients.ts:getPatientRecord",
    printDocumentState: "Documento de desarrollo / no uso clinico real",
    printClinicalUse: "development-only",
  },
  {
    route: "/print/pacientes/[patientId]/receta",
    domain: "print",
    lifecycle: "blocked",
    screenKind: "print",
    writePolicy: "blocked",
    paperPolicy: "carta",
    printOwnerEntity: "BlockedPrescriptionPlaceholder",
    printReadModel: "GET /api/v1/patients/{patient_id}/record",
    printApiClient: "apps/web/src/lib/api/patients.ts:getPatientRecord",
    printDocumentState: "Documento bloqueado: no valido para prescribir",
    printClinicalUse: "blocked",
    blockExpectation: ["Receta bloqueada", "Documento bloqueado: no valido para prescribir"],
  },
  {
    route: "/print/hospitalizacion/rondas",
    domain: "print",
    lifecycle: "complete",
    screenKind: "print",
    writePolicy: "none",
    paperPolicy: "carta",
    printOwnerEntity: "HospitalizationBoardItem + latest HospitalDailySheet",
    printReadModel: "GET /api/v1/hospitalization/active + GET /api/v1/hospitalization/patients/{patient_id}/daily-sheets",
    printApiClient: "apps/web/src/lib/api/hospitalization.ts:listActiveHospitalizations,listHospitalDailySheets",
    printDocumentState: "Documento operacional de desarrollo / no uso clinico real",
    printClinicalUse: "development-only",
  },
  {
    route: "/print/hospitalizacion/pacientes/[patientId]/hoja-diaria/[sheetId]",
    domain: "print",
    lifecycle: "complete",
    screenKind: "print",
    writePolicy: "none",
    paperPolicy: "carta",
    printOwnerEntity: "HospitalDailySheet + PatientRecordSnapshot",
    printReadModel: "GET /api/v1/patients/{patient_id}/record + GET /api/v1/hospitalization/patients/{patient_id}/daily-sheets",
    printApiClient: "apps/web/src/lib/api/patients.ts:getPatientRecord; apps/web/src/lib/api/hospitalization.ts:listHospitalDailySheets",
    printDocumentState: "Borrador/cerrada visible; sin firma legal digital",
    printClinicalUse: "development-only",
  },
  {
    route: "/print/hospitalizacion/pacientes/[patientId]/indicacion/[indicationId]",
    domain: "print",
    lifecycle: "complete",
    screenKind: "print",
    writePolicy: "none",
    paperPolicy: "carta",
    printOwnerEntity: "HospitalIndication + PatientRecordSnapshot",
    printReadModel: "GET /api/v1/patients/{patient_id}/record + GET /api/v1/hospitalization/patients/{patient_id}/indications",
    printApiClient: "apps/web/src/lib/api/patients.ts:getPatientRecord; apps/web/src/lib/api/hospitalization.ts:listHospitalIndications",
    printDocumentState: "Borrador/cerrada visible; no equivale a orden ejecutable ni firma legal",
    printClinicalUse: "development-only",
  },
];
